services:
  database:
    image: postgres
    container_name: book-shop-book-service
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=book-service
#    command: postgres -p 5432
    ports:
      - 5430:5432