server:
  port: 8087
spring:
  application:
    name: book-service
  datasource:
    username: admin
    password: admin
    url: jdbc:postgresql://localhost:5430/book-service
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
  cloud:
    discovery:
      enable: true
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8081/eureka

logging:
  level:
    org.hibernate:
      SQL: DEBUG
      type: TRACE
