server:
  port: 0
spring:
  application:
    name: book-service
  datasource:
    username: admin
    password: admin
    url: jdbc:postgresql://localhost:5432/book-service
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8081/eureka

apiGatewayAddress: http://localhost:8082