server:
  port: 8087
spring:
  kafka:
    bootstrap-servers: "localhost:9091"
    producer:
      keySerializer: "org.apache.kafka.common.serialization.StringSerializer"
      valueSerializer: "io.confluent.kafka.serializers.KafkaAvroSerializer"
      properties:
        schema:
          registry:
            url: "http://localhost:8085"
        specific.avro.reader: true
  application:
    name: book-service
  datasource:
    username: admin
    password: admin
    url: jdbc:postgresql://localhost:5430/book-service
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
  cloud:
    discovery:
      enable: true
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8081/eureka
